#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Tie-IxHash
Version  : 1.23
Release  : 27
URL      : https://cpan.metacpan.org/authors/id/C/CH/CHORNY/Tie-IxHash-1.23.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/C/CH/CHORNY/Tie-IxHash-1.23.tar.gz
Summary  : ordered associative arrays for Perl
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Tie-IxHash-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
implements ordered in-memory associative arrays.
It requires:
Perl Version 5.005 or later.

%package dev
Summary: dev components for the perl-Tie-IxHash package.
Group: Development
Provides: perl-Tie-IxHash-devel = %{version}-%{release}
Requires: perl-Tie-IxHash = %{version}-%{release}

%description dev
dev components for the perl-Tie-IxHash package.


%package perl
Summary: perl components for the perl-Tie-IxHash package.
Group: Default
Requires: perl-Tie-IxHash = %{version}-%{release}

%description perl
perl components for the perl-Tie-IxHash package.


%prep
%setup -q -n Tie-IxHash-1.23
cd %{_builddir}/Tie-IxHash-1.23

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Tie::IxHash.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
